In [1]:
import pandas as pd

sales = pd.read_csv("sales_data.csv", parse_dates=["order_date"], dtype={"product": "category", "category": "category"})

In [2]:
# Display the first 5 rows of the DataFrame
sales.head(5)

   order_id     product     category  quantity   price order_date
0         1      Laptop  Electronics         1  999.99 2023-01-15
1         2     T-shirt     Clothing         3   19.99 2023-01-16
2         3  Headphones  Electronics         2   49.99 2023-01-16
3         4      Jacket     Clothing         1   89.99 2023-01-17
4         5       Mouse  Electronics         5   29.99 2023-01-18

In [3]:
# Check the data types of each column
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    8 non-null      int64
 1   product     8 non-null      category
 2   category    8 non-null      category
 3   quantity    8 non-null      int64
 4   price       8 non-null      float64
 5   order_date  8 non-null      datetime64[ns]
dtypes: category(2), datetime64[ns](1), float64(1), int64(2)
memory usage: 892.0 bytes

In [4]:
# Summary statistics for numerical columns
sales[["quantity", "price"]].describe().round(2)

       quantity   price
count      8.00    8.00
mean       2.38  186.24
std        1.51  333.72
min        1.00   19.99
25%        1.00   37.49
50%        2.00   54.99
75%        3.25  117.49
max        5.00  999.99

In [5]:
# Check unique categories to confirm "Electronics" is correct
sales["category"].unique()

['Electronics', 'Clothing']
Categories (2, object): ['Clothing', 'Electronics']

In [6]:
# Create a new DataFrame containing only orders from the "Electronics" category.
electronics_sale = sales[sales["category"] == "Electronics"].reset_index(drop=True)

electronics_sale.head()

   order_id     product     category  quantity   price order_date
0         1      Laptop  Electronics         1  999.99 2023-01-15
1         3  Headphones  Electronics         2   49.99 2023-01-16
2         5       Mouse  Electronics         5   29.99 2023-01-18
3         7     Monitor  Electronics         1  199.99 2023-01-19
4         8    Keyboard  Electronics         4   39.99 2023-01-20

In [7]:
# Check unique quantities to confirm filter condition
sales["quantity"].unique()

array([1, 3, 2, 5, 4])

In [8]:
# Create another DataFrame with orders where the quantity sold is greater than 2.
big_orders = sales[sales["quantity"] > 2].reset_index(drop=True)

big_orders.head()

   order_id   product     category  quantity  price order_date
0         2   T-shirt     Clothing         3  19.99 2023-01-16
1         5     Mouse  Electronics         5  29.99 2023-01-18
2         8  Keyboard  Electronics         4  39.99 2023-01-20

In [9]:
# Add a new column total_sales by multiplying quantity and price
sales["total_sales"] = sales["quantity"] * sales["price"]

In [10]:
# Calculate the total sales
sales["total_sales"].sum().round(2)

np.float64(1879.81)

In [11]:
# Find the average price of products in the "Clothing" category
sales.loc[sales["category"] == "Clothing"]["price"].mean().round(2)

np.float64(56.66)